sonar.projectKey=furniture-management
sonar.projectName=Furniture Management DevOps
sonar.projectVersion=1.0

# Path to source directories (current directory)
sonar.sources=.

# Exclude directories that shouldn't be scanned
sonar.exclusions=node_modules/**, database/**, odc-reports/**, **/*.json, **/*.xml

# Encoding of the source code
sonar.sourceEncoding=UTF-8
